// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfDomainRule struct {
	_     structs.HostLayout
	Qname [64]uint8
	Qlen  uint8
	_     [3]byte
	Mark  uint32
}

type BpfLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	RevQname  [64]uint8
}

type BpfRdnsKey struct {
	_    structs.HostLayout
	Addr uint32
}

type BpfRdnsVal struct {
	_     structs.HostLayout
	Qlen  uint8
	Qname [64]uint8
}

type BpfRoutingDecision struct {
	_    structs.HostLayout
	Mark uint32
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	CgroupConnect4DomainRoute *ebpf.ProgramSpec `ebpf:"cgroup_connect4_domain_route"`
	TcIngressDnsParse         *ebpf.ProgramSpec `ebpf:"tc_ingress_dns_parse"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	DomainLpm        *ebpf.MapSpec `ebpf:"domain_lpm"`
	DomainRules      *ebpf.MapSpec `ebpf:"domain_rules"`
	Rdns             *ebpf.MapSpec `ebpf:"rdns"`
	RoutingDecisions *ebpf.MapSpec `ebpf:"routing_decisions"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	DomainLpm        *ebpf.Map `ebpf:"domain_lpm"`
	DomainRules      *ebpf.Map `ebpf:"domain_rules"`
	Rdns             *ebpf.Map `ebpf:"rdns"`
	RoutingDecisions *ebpf.Map `ebpf:"routing_decisions"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.DomainLpm,
		m.DomainRules,
		m.Rdns,
		m.RoutingDecisions,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	CgroupConnect4DomainRoute *ebpf.Program `ebpf:"cgroup_connect4_domain_route"`
	TcIngressDnsParse         *ebpf.Program `ebpf:"tc_ingress_dns_parse"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.CgroupConnect4DomainRoute,
		p.TcIngressDnsParse,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
